### PR TITLE
Cocoapods 1.0 fixes

### PR DESCRIPTION
**Pull request by paulz**
Fix preserve headers in podspec
This allows installing RestKit using cocoapods 1.0.0

### CODE REVIEW

**Comment by segiddins** [comment]
Hey, can you please get rid of the merge commit and the whitespace changed and update the locked version of CocoaPods in the Gemfile so we can test that things work on CI? Thanks! (I do think that getting rid of the `header_mappings_dir` will break things for users, as fully qualified imports will no longer work)

**Comment by paulz** [comment]
Thank you for the review, @segiddins! 
The code is from @mcfedr fork, we are just grateful to find it, as it solves our Cocoapods 1.0 issue.

Dear @mcfedr, thank you for your change to RestKit. 

Would you be able to comment here or update this pull request? Or make another pull request?

Awesome job, open source community!

**Comment by mcfedr** [comment]
I'll see if I can address these issues today

I also want to add a link from here to https://github.com/RestKit/RestKit/issues/2356 as lots of people are asking

**Comment by markst** [comment]
🎉

**Comment by markst** [comment]
all seems good except:
image

**Comment by valeriomazzeo** [comment]
As I explained in the other issue https://github.com/RestKit/RestKit/issues/2356 I get exactly the same result / error with the RestKit development branch.

**Comment by mcfedr** [comment]
Update the branch to make it a cleaner pull request.

I have included the commit e7ad20d which is actually not 100% essential for this
- without it `use_frameworks!` doesnt work
- it also requires the user to have `pod 'AFNetworking', :git => 'https://github.com/mcfedr/AFNetworking.git', :branch => 'reachability'` in his Podfile

  Unfortunately I cannot make RestKit depend on a version from git and I have reached out to AFNetworking and they won't make a new patch version of 1.x

Without e7ad20d and without `use_frameworks!` RestKit is usable with Cocoapods 1.0 with the changes from only b2063b7

The changes in b2063b7 are not backwards compatible. As @segiddins points out, anyone importing a header that was in a directory before will have to change the path or just use `@import RestKit` - which is probably the recommended way anyway and is only a small change to make.

So, no easy way to go here.

**Comment by valeriomazzeo** [comment]
Please have a look at https://github.com/RestKit/RestKit/pull/2434

**Pull request closed without merging**
