### PR TITLE
Change paths to allow compiling as module

### PR DESCRIPTION
**Pull request by jlampa**
This solves https://github.com/RestKit/RestKit/issues/2356

### CODE REVIEW

**Comment by falkobuttler** [comment]
@jlampa Travis fails due to missing includes. It looks like something is still missing in this PR to make the build work.

**Comment by mcfedr** [comment]
This is probably not backwards compatible, if anyone is directly including a sub-part of restkit

**Comment by segiddins** [comment]
Closing in favor of the other open PR

**Comment by paulz** [comment]
@segiddins what is the other open PR?

**Comment by segiddins** [comment]
https://github.com/RestKit/RestKit/pull/2404, I think

**Pull request closed without merging**
