### PR TITLE
Shouldn’t validate content type if there is no content

### PR DESCRIPTION
**Pull request by stnslw**
Content-Type should not be validated when there is no content for every status code, not only 204.
For example: according to RFC it is valid to provide no content for responses with 200 status code. In this case content type validation should not be performed.

Also, this fix aligns the implementation with AFNetworking, which uses the same rule for skipping Content-Type validation.

### CODE REVIEW

**Comment by segiddins** [comment]
Looks like CI is failing

**Comment by stnslw** [comment]
The test case that is failing is not even reaching the changes introduced in the pull request. Also all of the tests are successful when Im executing them locally. 
Could it be a CI test server configuration issue?

**Comment by segiddins** [comment]
Could be

**Comment by valeriomazzeo** [comment]
@stnslw it is a CI issue that I finally had the time to fix.

Pull request looks good, will merge once 0.27.1 is out

**Comment by valeriomazzeo** [comment]
@stnslw could you please update from `development` and make sure tests are green?

CI is back to business :)

**Comment by stnslw** [comment]
@valeriomazzeo Nice 👍 Its passing now

**Pull request merged**
