### PR TITLE
Don't Unlock In-Memory Cache Until Flush is Completed

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Since #2370, I've noticed a reduced occurrence of duplicated objects, but still some. This is the cause – since we flush the caches asynchronously, we need to keep the outer cache locked until all inner caches are flushed.

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by mvoong** [comment]
@Adlai-Holler thanks for this. I've noticed your `MoreInMemoryCacheWork` branch. Is that just a refactor or does it fix a new issue?

**Comment by Adlai-Holler** [comment]
There are still occurrences of duplicated objects in my (heavy) usage, so I'm trying to squash all the rest of the instances. The branch works better but still not perfectly.

**Comment by ILI4S** [comment]
thank you @Adlai-Holler for your work on the memory cache branch. we've been merging your changes into our branch and have noticed the same results as you: it works better--much better, even--but still not perfectly :)

**Comment by Adlai-Holler** [comment]
You're welcome @ILI4S thanks for commenting. It encourages me to keep at it!

**Pull request merged**
