### PR TITLE
Use framework-style import statements

### LINKED ISSUE #2288: Fix imports in public header files
Imports in public header files should be `#import <RestKit/Subdirectory/RKHeader.h>` instead of `#import "RKHeader.h"`

This is required for RestKit to be compatible with future CocoaPods version because of CocoaPods/CocoaPods#4057 (The `HEADER_SEARCH_PATHS` will no longer be constructed recursively) introduced in 0.39.0.beta.1.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #2288.

Done almost entirely with the following script:

```ruby
require 'pathname'

files_by_name = Pathname.glob('Code/**/*.{h,m}').group_by(&:basename)
files_by_name.each_value do |files|
  files.each do |file|
    content = file.read
    content.gsub!(/#import "([^"]*)"/) {
      p $1
      path = Array(files_by_name[Pathname($1)]).first
      if path
        path = path.each_filename.drop_while { |c| c != 'Code' }.drop(1).join('/')
        "#import <RestKit/#{path}>"
      else
        %(#import "#{$1}")
      end
    }
    file.open('w') { |f| f.write content }
  end
end
```

\c @0xced

### CODE REVIEW

**Comment by 0xced** [comment]
Great work! There are nonetheless a few remaining issues:

* **RKLog.h** does `#import "lcl_RK.h"` but `lcl_RK.h` is buried inside `Vendor/LibComponentLogging/Core` which is not exposed in the podspec. Workaround: add `$(PODS_ROOT)/RestKit/Vendor/LibComponentLogging/Core` in the app’s `HEADER_SEARCH_PATHS` but it’s damn ugly.

* **lcl_RK.h** has three different `#import "lcl_config_*.h"` which don’t work either. Replacing them with `#import <RestKit/Support/lcl_config_*.h>` solves the compilation issue.

* Not really an issue but importing RestKit headers from `.m` files with brackets is not really required. Importing them with quotes would be fine too. It’s only required in headers because they are ultimately _#imported_ by the app.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/pull/4267 will also be required

**Comment by segiddins** [comment]
This should now pass :)

**Comment by segiddins** [comment]
@0xced if you want to take a look at this

**Comment by 0xced** [comment]
I'll have a look tomorrow or on Monday.

**Comment by segiddins** [comment]
👍🏻 thanks, and sorry it took me so long to circle back

**Comment by 0xced** [comment]
I just tested the `seg-bracket-imports` branch (d6a0f1ab5c90fc19294d54b8c8dd9e7857565f81) with CocoaPods 0.39.0 and everything compiles fine. 😀 Thanks @segiddins!

**Comment by segiddins** [comment]
Did you try with Xcode 7.1, per chance?

**Comment by 0xced** [comment]
Everything is OK with 6.4, 7.0.1 and 7.1.

**Comment by segiddins** [comment]
🎉 yay! I'll merge this tonight and ship a 0.26!

**Comment by skydivedan** [comment]
so it is going to be merged now?

maybe now?

or now?

**Comment by segiddins** [comment]
I haven't been on a computer since yesterday morning, I'll merge this when I get a chance.

**Comment by agoldoor** [comment]
Hey, are you going to merge this and release a new cocoapod? I know lots of people are waiting with broken builds.

**Comment by segiddins** [comment]
@agoldoor It's failing at the moment and I don't know why. I don't personally use RestKit any more, and I maintain it in my free time. I'll get around to it when I can, otherwise other people are more than welcome to make pull requests.

**Comment by timbodeit** [comment]
The error in `pod lib lint` was related to the umbrella header generation in CocoaPods.
It did not yet take into account the directory structure of the header files, that has only been preserved since [CocoaPods/CocoaPods#4267](https://github.com/CocoaPods/CocoaPods/pull/4267)

I filed [a pull request](https://github.com/CocoaPods/CocoaPods/pull/4509) to fix this.

In addition to the one fixed error, there still are 5 warnings though.

**Comment by segiddins** [comment]
Ah, thanks @timbodeit for investigating!

**Comment by timbodeit** [comment]
Shouldn't the `__has_include` statements also be converted to framework style paths?

**Comment by segiddins** [comment]
This is finally green again, merging.

**Pull request merged**
