### PR TITLE
Add support for inclusion of RestKit as a Clang Module

### PR DESCRIPTION
**Pull request by segiddins**
Maintains support for the use of vendored dependencies inside the main Xcode project itself, rather than using subprojects.

@blakewatters this is necessary to support the use of RestKit as a proper framework via CocoaPods.

### CODE REVIEW

**Comment by aharren** [comment]
I've opened an issue: https://github.com/aharren/LibComponentLogging-Core/issues/26

Looks like the implicit transformation of #includes to an import breaks the X macros for the log components.

**Comment by segiddins** [comment]
It's the fact that, under modules, includes aren't textual. 

-Samuel E. Giddins

On Jan 26, 2015, at 10:29 PM, Arne Harren <notifications@github.com> wrote:

I've opened an issue: aharren/LibComponentLogging-Core#26

Looks like the implicit transformation of #includes to an import breaks the X macros for the log components.

**Comment by licx** [comment]
Any news on this? Cocoapods 0.36 is out but Restkit still doesn't work when compiled with the ```use_frameworks!``` option

**Comment by aharren** [comment]
Sorry, there's no general solution for LCL yet. Perhaps it's possible to add the changes to `lcl_config_components_RK.h` via a #ifdef and keep the old definition of _RKlcl_component. Then, we can change RestKit and adapt LCL independently and we don't break the un-embedding.

**Comment by segiddins** [comment]
LCL hasn't been the holdup, I'm fine with me just committing those changes until LCL has been updated. I just need to work out how to fix everything else :)

**Comment by bonebox** [comment]
@segiddins Have you tried including the seg-clang-modules branch in a podspec?  I was playing around with it and it does build successfully in a dynamic framework if included in a Podfile, however, I attempted to include it in a podspec that I created for my framework, and it won't pass the lint, giving the error below.

```
    - ERROR |  RestKit/Code/ObjectMapping/RKObjectMapping.h:25:12: error: include of non-modular header inside framework module 'RestKit.RKObjectMapping'
    - ERROR |  RestKit/Code/ObjectMapping.h:30:12: error: include of non-modular header inside framework module 'RestKit.ObjectMapping'
    - ERROR |  Test.swift:9:8: error: could not build Objective-C module 'RestKit'
```

**Comment by segiddins** [comment]
This PR needs a lot of work, but I'd definitely appreciate contributions to fix things!

-Samuel E. Giddins

On Mar 20, 2015, at 8:24 AM, Jeremy Bone <notifications@github.com> wrote:

@segiddins Have you tried including the seg-clang-modules branch in a podspec? I was playing around with it and it does build successfully in a dynamic framework if included in a Podfile, however, I attempted to include it in a podspec that I created for my framework, and it won't pass the lint, giving the error below.

    - ERROR |  RestKit/Code/ObjectMapping/RKObjectMapping.h:25:12: error: include of non-modular header inside framework module 'RestKit.RKObjectMapping'
    - ERROR |  RestKit/Code/ObjectMapping.h:30:12: error: include of non-modular header inside framework module 'RestKit.ObjectMapping'
    - ERROR |  Test.swift:9:8: error: could not build Objective-C module 'RestKit'

**Comment by bonebox** [comment]
I haven't found a solution yet, but if I do I'll definitely add it.  I pointed a test project to my local podspec for my dynamic framework that has the RestKit dependency (using seg-clang-modules branch), and confirmed that I get the same error when I build it manually.  What's weird is on the initial build I get the error I posted above.  Then I tried pointing it to ```#import "RKValueTransformers.h"``` instead of ```#   import <RKValueTransformers/RKValueTransformers.h>``` and as expected, get the error: ```'RKValueTransformers.h' file not found.``` But then, after I set the file back like it originally was and build again, it builds successfully.

**Comment by bonebox** [comment]
I'm starting to think it may be a CocoaPods related issue, perhaps with the RestKit podspec.

**Comment by segiddins** [comment]
No, it's definitely a RestKit issue.

**Comment by segiddins** [comment]
@mrackwitz if you're ever looking for a random thing to work on, I'd appreciate some help getting this to work.

**Comment by besi** [comment]
+1

**Comment by besi** [comment]
I did fallback to not using `use_frameworks!` but now I would like to use the cocoapod [XCGLogger](https://github.com/DaveWoodCom/XCGLogger) which is a swift framework and requires the `use_frameworks!` option.

It looks like I can't use that library until RestKit allows to use it.

**Comment by segiddins** [comment]
@besi I'm sorry, I just haven't had the time to dedicate to fixing this up. Feel free to make a pull request improving the situation!

**Comment by besi** [comment]
@segiddins: I just ran into another situation where I would like to use a new swift cocoapod. Could you compile a list of things which would need to be fixed in order for RestKit to be `use_frameworks!`-friendly?

**Comment by pat2man** [comment]
@segiddins Can you clarify what you mean when you say the pull request needs a lot of work? I am definitely down to chip in if it means we can get framework support in cocoa pods.

**Comment by segiddins** [comment]
@pat2man the easiest solution is probably going to be properly using the submodule dependencies as subprojects, so we can use namespaced imports everywhere.

**Comment by pat2man** [comment]
@segiddins makes sense, thanks for the update.

**Comment by erikackermann** [comment]
@segiddins what still needs to be done on this PR before it can be merged in?

**Comment by segiddins** [comment]
The example apps need to compile (and CI needs to pass)

-Samuel E. Giddins

On Jun 16, 2015, at 7:30 AM, Erik Ackermann <notifications@github.com> wrote:

@segiddins what still needs to be done on this PR before it can be merged in?

**Comment by besi** [comment]
I am successfully using this branch in my project now:

    pod 'RestKit', :git => 'https://github.com/RestKit/RestKit.git', branch: 'seg-clang-modules'

:+1:

**Comment by adolfo** [comment]
@erikackermann I opened #2254 to fix the issues with the example projects and CI.
@segiddins could let me know if there is anything else you need in order to get this merged in?

**Comment by maxep** [comment]
Hi @segiddins & @adolfo 

Thanks very much for your hard work! I've developed a library called DiscogsAPI based on RestKit and I'm trying to use it in a swift project.
To try your recent changes I've setted the podfile as:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "DiscogsAPIDemo" do
    platform :ios, '8.0'
    pod 'RestKit', :head
	pod 'DiscogsAPI', :path => '../'
end
```
But when I build it, I still get errors like:
```
While building module 'RestKit' imported from /Users/maximeepain/Gits/DiscogsAPI/Demo-swift/Pods/RestKit/Code/ObjectMapping.h:23:
In file included from <module-includes>:1:
In file included from /Users/maximeepain/Gits/DiscogsAPI/Demo-swift/Pods/Target Support Files/RestKit/RestKit-umbrella.h:3:
In file included from /Users/maximeepain/Gits/DiscogsAPI/Demo-swift/Pods/RestKit/Code/CoreData.h:22:
/Users/maximeepain/Gits/DiscogsAPI/Demo-swift/Pods/RestKit/Code/ObjectMapping.h:21:9: error: include of non-modular header inside framework module 'RestKit.ObjectMapping' [-Werror,-Wnon-modular-include-in-framework-module]
#import <RKValueTransformers/RKValueTransformers.h>
        ^
```
am I missing something ?

Thanks again,

Maxime

**Comment by segiddins** [comment]
Can you try depending directly on the development Branch?

**Comment by maxep** [comment]
Same result with:
```ruby
source 'https://github.com/CocoaPods/Specs.git'

target "DiscogsAPIDemo" do
    platform :ios, '8.0'
    use_frameworks!
    pod 'RestKit', :git => 'https://github.com/RestKit/RestKit.git', :branch => 'development'
	pod 'DiscogsAPI', :path => '../'
end
```

**Comment by adolfo** [comment]
@maxep CocoaPods version?

**Comment by adolfo** [comment]
@maxep looks like `DiscogsAPI.podspec` includes RestKit as a dependency:

    s.dependency 'RestKit'
    ...
    // Make RestKit globally available
    #import <RestKit/RestKit.h>

**Comment by maxep** [comment]
@adolfo ,
Is it an issue? cocoapods takes care of including dependencies once so it gets code from the dev branch.

**Comment by cesar-oyarzun-m** [comment]
Hi I'm having the same issue my project give error here is my pod file 

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ExpSDK_Example', :exclusive => true do
  pod "ExpSDK", :path => "../"
  pod 'RestKit', :git => 'https://github.com/RestKit/RestKit.git', :branch => 'development'
end

target 'ExpSDK_Tests', :exclusive => true do
  pod "ExpSDK", :path => "../"
  pod 'Kiwi'
end
use_frameworks!

**Comment by briangbutterfield** [comment]
I am having the same problem using development branch as @cesar-oyarzun-m.  Have there been any new updates or fixes to this issue.

I am trying to reference RestKit (via CocoaPods) in a Swift Framework.

**Comment by cesar-oyarzun-m** [comment]
@briangbutterfield Thanks but I already fix the problem!!

**Comment by briangbutterfield** [comment]
@cesar-oyarzun-m Can I ask how you fixed your problem?

**Comment by andrejbroncek** [comment]
@cesar-oyarzun-m Could you please let us know how did you solve this problem? Thank you very much. 

I am now using dev branch of RestKit, but still getting errors regarding non-modular headers. I am basically stucked now with my project.

**Comment by tskulbru** [comment]
Im trying to use restkit as a dynamic framework, through cocoapods's `use_framework!` and experience the same issues you guys are having. How on earth did you fix this?

**Comment by briangbutterfield** [comment]
I never did get it to work. I used a different swift-based library.

**Comment by dincho** [comment]
@briangbutterfield :+1:

**Comment by andrejbroncek** [comment]
Me neither. What I did was that I dropped the Swift library in my project and removed `use_framework!` from Podfile.

**Comment by tskulbru** [comment]
So, I actually solved this. I am now using RestKit as a dynamic framework. The problem was two-fold.
* The latest version of restkit `0.26.0` doesnt' build properly using cocoapods. The solution was to use `0.25.0` for the time being. This made the missing headers actually be included and build. See more  here #2356

* Secondly, because I use CocoaLumberjack which RestKit has a dependency on (if its found), I either had to include it as a subspec of restkit or include it as a dependency through `post_install` in my `Podfile`. Read more: http://stackoverflow.com/questions/31923006/restkit-and-cocoalumberjack-integrated-as-frameworks-in-xcode7

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.to_s == 'RestKit'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework "CocoaLumberjack"'
      end
    end
  end
end
```

Hope this helps anyone else having the same issues I had.

**Comment by hernangonzalez** [comment]
Hey Guys,

Have the same issue, I had to rollback to 0.25.0. Any alternative to this? I would like to keep RestKit up to date too. 
@tskulbru did you manage to upgrade to 0.26 ?

Regards,
H.

**Comment by tskulbru** [comment]
@hernangonzalez no I haven't tried again, but it seems like https://github.com/RestKit/RestKit/commit/cdfe23ff3df684e7cc97ac85578266ec6d2a2449 fixes it. Either try to use HEAD or wait for next release. But I haven't tried it so no guarantees. The commit closed #2356 .

**Comment by cesar-oyarzun-m** [comment]
I have this configuration @briangbutterfield @andrejbroncek 

    source 'https://github.com/CocoaPods/Specs.git'
    use_frameworks!

    target 'ExpSwift_Example', :exclusive => true do
    pod "ExpSwift", :path => "../"
    end

    target 'ExpSwift_Tests', :exclusive => true do
    pod "ExpSwift", :path => "../"
    end

and the .podspec

      s.platform     = :ios, '8.0'
    s.requires_arc = true

    s.source_files = 'Pod/Classes/**/*'
    s.resource_bundles = {
    'ExpSwift' => ['Pod/Assets/*.png']
    }

    # s.public_header_files = 'Pod/Classes/**/*.h'
    # s.frameworks = 'UIKit', 'MapKit'
    s.dependency 'PromiseKit','3.0.0'
    s.dependency 'Alamofire','3.1.2'
    s.dependency 'Socket.IO-Client-Swift','4.1.2'
    s.dependency 'JSONWebToken','1.4.1'
    end

**Comment by r3econ** [comment]
Has this been fixed? I'm using RestKit 0.26 and when I addes use_frameworks! to the podfile RestKit is unusable. I'm getting import errors?

**Comment by tskulbru** [comment]
@r3econ no, its not possible on `0.26` you have to either use `HEAD` or continue to use `0.25`

**Pull request merged**
