### PR TITLE
Fault updated objects before merging changes into mainQueueManagedObject...

### PR DESCRIPTION
**Pull request by ppierson**
...Context.

This enables NSFetchedResultsController to update and re-sort its fetch results and to call its delegate methods
in response to these updates.
See http://stackoverflow.com/questions/3923826/nsfetchedresultscontroller-with-predicate-ignores-changes-merged-from-different
for issue details.

-----

I am having an issue where an instance of NSFetchedResultsController is not responding to updates to its non-faulted fetched objects when updates are merged into the mainQueueManagedObjectContext. It is not re-sorting its data set, nor is it calling its delegate methods. However, once I scroll through my tableview and fault some of the fetched objects into memory, the NSFetchedResultsController does respond to changes to those objects. 

I've found a similar issue on stackoverflow: http://stackoverflow.com/a/3927811/489376 and have made similar changes to `[RKManagedObjectStore handleManagedObjectContextDidSaveNotification:]` to resolve this issue.

### CODE REVIEW

**Comment by segiddins** [comment]
Please add test coverage that proves you've fixed the issue

**Comment by segiddins** [comment]
@ppierson tests?

**Comment by ppierson** [comment]
@segiddins Sorry, I was away and this slipped my mind. I'll set some time this week to wrap this up.

**Comment by ppierson** [comment]
I added a test case that checks to see if an NSFetchedResultsController observes updates to Managed Objects merged from another context.

**Comment by segiddins** [comment]
Excellent, thanks @ppierson !

**Pull request merged**
