### PR TITLE
Perform access to NSManagedObjectContext's properties only on its queue

### PR DESCRIPTION
**Pull request by morozkin**
Hi!

I found a few places where wrong accessing to NSManagedObjectContext's properties is performing. We must access it's properties only on the queue otherwise we will faced with concurrency problems.

### CODE REVIEW

**Comment by morozkin** [comment]
@valeriomazzeo WDYT?

**Comment by valeriomazzeo** [comment]
@morozkin if you can reproduce the issue in a test, I would be more than happy to have a look

**Comment by morozkin** [comment]
@valeriomazzeo I added the test for `appropriateObjectRequestOperationWithObject:method:path:parameters` method of `RKObjectManager`. It always ends with the crash on the development branch and successfully finishes on my branch.

**Comment by valeriomazzeo** [comment]
@morozkin looks good, thanks for that.

I just need to understand why travis-ci is failing...

**Comment by morozkin** [comment]
@valeriomazzeo Do you have any news about CI failing?

**Comment by valeriomazzeo** [comment]
I don't have much time to dig into that, and unfortunately it doesn't look like it's something obvious

**Pull request merged**
