### PR TITLE
KVC with array access

### PR DESCRIPTION
**Pull request by oligriffiths**
Implemented KVC with array access.

This is something that I've run into on many occasions and I've seen other people on the google group have also.

People want to be able to do the following mapping:

foo[1].bar[0].url : url

I've implemented this by regex chaecking the keypath, if it contains a digit then splitting the string by [\d+] and performing KVC on the middle parts and array access on the indexes.

NSLogs for failure to match inline with KVC and returns nil.

Test included in RKMappingOperationTest:testSourceKeyWithKVCArraySupport

### CODE REVIEW

**Comment by oligriffiths** [comment]
Sorry about the master merge

**Comment by segiddins** [comment]
I'm really loathe to add categories on NSObject (or any class we don't own, for that matter)

**Comment by oligriffiths** [comment]
Fair enough. This can be added to the mapper class as a private function in that case. 

Does that work for you?

**Comment by segiddins** [comment]
If it doesn't affect performance in the common case, potentially. I know @percysnoodle had tried building custom KVC stuff in the past. 

-Samuel E. Giddins

On May 17, 2015, at 11:21 AM, Oli Griffiths <notifications@github.com> wrote:

Fair enough. This can be added to the mapper class as a private function in that case. 

Does that work for you?

**Comment by oligriffiths** [comment]
Removed category and moved to RKMappingOperation. Defaults to default KVC first, if no match, as when using foo[0].bar syntax, regex match and KVC array logic is performed

**Comment by oligriffiths** [comment]
For some reason the new commits arent showing on this PR, but they're on the branch and I can submit a new PR with them....

**Pull request closed without merging**
