### PR TITLE
Fix for issue #2225

### PR DESCRIPTION
**Pull request by deberle**
Improve check for deleted managedObject.

### CODE REVIEW

**Comment by segiddins** [comment]
Can you please add test coverage for this?

**Comment by deberle** [comment]
I'm afraid I can't right now. I do not have the experience with the framework yet. So I must leave this open  until I have a better feeling for RestKit or somebody more skilled picks this up.

**Comment by segiddins** [comment]
I don't think we want 9dac8a6

**Comment by segiddins** [comment]
Closing due to inactivity.

**Pull request closed without merging**
