### PR TITLE
Allow the use of URL parameters when creating a paginator.

### PR DESCRIPTION
**Pull request by autresphere**

### CODE REVIEW

**Comment by segiddins** [comment]
This is missing tests.

**Comment by autresphere** [comment]
Not sure about what to test.
Would something like ```[RKPaginatorTest testInitCopiesPatternURLWithParameters]``` be enough ?

**Comment by segiddins** [comment]
And also creating URLs with the paginator. 

-Samuel E. Giddins

On Jan 26, 2015, at 2:59 AM, Philippe Converset <notifications@github.com> wrote:

Not sure about what to test.
Would something like [RKPaginatorTest testInitCopiesPatternURLWithParameters] be enough ?

**Comment by autresphere** [comment]
This PR is canceled and replaced bu #2174

**Pull request closed without merging**
