### PR TITLE
Fix for issue #1784. Mapping result is available in willSaveMappingContextBlock

### PR DESCRIPTION
**Pull request by vilinskiy-playdayteam**

### CODE REVIEW

**Comment by vilinskiy-playdayteam** [comment]
xcodebuild: error: Failed to build workspace RestKit with scheme RestKitTests.
Reason: The run destination iPad 2 is not valid for Testing the scheme 'RestKitTests'

What can this error message mean?

**Comment by segiddins** [comment]
The test failed before your change?

**Comment by vilinskiy-playdayteam** [comment]
Tests has not even started for iOS due to the error above. But today I reopened the same pull request to restart build and it finished with success this time.
I think the problem was with recent XCode update that, I suppose, was also performed on Travis server.

**Comment by segiddins** [comment]
That wasn't my question. I'm asking whether the test you wrote failed before you applied your fix.

**Comment by vilinskiy-playdayteam** [comment]
Yes, the mapping result is nil on the latest development commit

**Comment by djmadcat** [comment]
Please, close #1784 if it was fixed.
Thanks=)

**Pull request merged**
