### PR TITLE
Put CocoaLumberjack Logging into separate subspec (Fixes Issue #2262)

### PR DESCRIPTION
**Pull request by timbodeit**
Previously `RKLumberjackLogger` was used automatically if CocoaLumberjack is present.
This was realized by checking if the `DDLog.h` Header file is available. This approach works great with static libraries, but is problematic when building RestKit as a framework.

When built as a framework, RestKit needs to be explicitly linked against CocoaLumberjack. Otherwise it will find the Header files, but fail at the linking stage.

My Approach:
Moving `RKLumberjackLogger` into a separate subspec (RestKit/CocoaLumberjack).  
Inside that subspec also setting a preprocessor macro `RKLOG_USE_COCOALUMBERJACK`, similar to the one already in place `RKLOG_USE_NSLOGGER`.  
Only using CocoaLumberjack for logging, if that macro is set.

This fixes the problems when using cocoapods `use_frameworks!` options, that I described in issue #2262 .

Problems:
- Introducing the subspec and macro will change RestKits behavior in existing projects (even when static libraries are used).
- **`[RESOLVED]`** RestKit currently uses old 1.9.x CocoaLumberjack API (see #2263 ).  
_Adding it as an explicit dependency in a subspec causes `pod lib lint` to show three resulting errors, that would previously show up at a later stage (when RestKit and Cocoalumberjack together are included in a project)._

### CODE REVIEW

**Comment by segiddins** [comment]
Please take a look at the CI failures: https://travis-ci.org/RestKit/RestKit/builds/75110589#L1670

**Comment by timbodeit** [comment]
I already did. Partly they are related to #2263.
Will get on it in the next couple of days

**Comment by timbodeit** [comment]
@segiddins If you find the time for it, it would be awesome if you could take another look at this pull request and give me some feedback on it.

I've thought some more about the problem with the behavior changes compared to previous versions.

I could only come up with two options. Maybe you might have a better idea how to solve this:

##### 1. Move CocoaLumberjack related code to subspec and use `RKLOG_USE_COCOALUMBERJACK` macro.
  **Pros:**
    - Might be better for people using frameworks and not using CocoaPods. If they don't want to use CocoaLumberjack, they don't have to worry about linking RestKit against it.
    - Consistent with `RKLOG_USE_NSLOGGER`

  **Cons:**
    - Changes behavior for everybody using RestKit as a static library. They have to add "RestKit/CocoaLumberjack" to their Podfile if they want RestKit to keep logging into Lumberjack.
##### 2. Move CocoaLumberjack related code to subspec and decide based on availability of `RKLumberjackLogger.h` (which is part of the subspec)
  **Pros:**
    - Doesn't change behavior for people using RestKit as a static library without CocoaPods  

  **Cons:**
    - Still changes behavior for people using RestKit as a static library with CocoaPods. They have to add "RestKit/CocoaLumberjack" to their Podfile if they want RestKit to keep logging into Lumberjack.
    - People using RestKit as a framework without CocoaPods could still face issues, when not linking it against CocoaLumberjack.

---

As I said: Those were the only two solutions I could come up with. Any better suggestions are highly appreciated.

Nonetheless, I believe the ability to use CocoaLumberjack and RestKit (together) as frameworks with CocoaPods overweights the mentioned drawbacks. Especially since frameworks are becoming increasingly relevant over static libraries.

Currently it is not possible to integrate CocoaLumberjack and RestKit as framworks into the same project without making additional modifications after running `pod install`.

**Comment by timbodeit** [comment]
Removed c4a523a due to new CocoaLumberjack release that fixed the silenced warning and rebased onto RestKit:development

**Comment by segiddins** [comment]
I'd prefer to put the lumberjack specific code behind a subspec -- I'm ok with people upgrading having to explicitly specify the subspec.

**Comment by timbodeit** [comment]
That's nice to hear ☺️

Just to clarify:
Both of the mentioned options would involve putting the Lumberjack specific code into a subspec.
Option 1 is the current implementation in the PR. Option 2 would be a possible Alternative.

`RKLog.m` where the actual selection of the used logging framework happens is part of Support which gets included in Core. Here the selection previously happened by checking if the Lumberjack Headers are available, which doesn't work with framework for the above mentioned reasons.
Option 1 would be to use a `RKLOG_USE_COCOALUMBERJACK` that is set in the subspec definition.
Option 2 would check the availability of RKLumberjack.h which depends on whether the subspec is included. 

The only real difference between the two would be for people not using CocoaPods, but rather including RestKit manually.

**Comment by segiddins** [comment]
Sorry, I didn't fully understand. If you don't mind, I'd prefer using a has include check.

**Comment by timbodeit** [comment]
See 0d41f8b

**Comment by segiddins** [comment]
:fireworks:

**Pull request merged**
