### PR TITLE
Release v0.27.1

### PR DESCRIPTION
**Pull request by valeriomazzeo**

### CODE REVIEW

**Comment by jspaletavert** [comment]
Good Alaskan morning,

Just wondering when 0.27.1 will be officially released?  It looks like prep for release stalled a couple of weeks ago.

**Comment by valeriomazzeo** [comment]
@jspaletavert I have started the process, but CI is not happy yet and haven't had much time to dedicate to it :(

**Comment by jspaletavert** [comment]
thanks for the update

**Comment by almsta** [comment]
Any news on releasing the 0.27.1 version?

**Comment by ecstasy2** [comment]
If anyone is willing to point to a direction on how we could fix the CI failure I am happy to try to get a fix for it

**Comment by valeriomazzeo** [comment]
@ecstasy2 the problem seemed caused by `pod lib lint`.

I remember I tried to migrate the project to Xcode 8, to be able to use the new Travis CI OS Image https://github.com/RestKit/RestKit/pull/2467 but that caused other problems in some of the tests:
```
RKManagedObjectRequestOperationTest
  testThatManuallyCreatedObjectsThatAreNotSavedBeforePostingAreNotDuplicatedWhenMappedWithInMemoryManagedObjectCache, expected: <RKHuman: 0x7fb91d94bee0> (entity: Human; id: 0x7fb91d962a30 <x-coredata:///Human/tBABC1BFC-F219-4E85-9A41-5B41E045BCFA432> ; data: <fault>), got: <RKHuman: 0x7fb91bf67690> (entity: Human; id: 0xd0000000000400e2 <x-coredata://8C52C3CE-ED30-4C0A-9A64-B06897CDF661/Human/p1> ; data: {\n    age = 0;\n    birthday = nil;\n    catIDs = nil;\n    cats = "<relationship fault: 0x7fb91da4f6a0 'cats'>";\n    catsInOrderByAge = "<relationship fault: 0x7fb91bffae10 'catsInOrderByAge'>";\n    createdAt = nil;\n    favoriteCat = nil;\n    favoriteCatID = 0;\n    favoriteColors = nil;\n    friends = "<relationship fault: 0x7fb91bff7540 'friends'>";\n    friendsInTheOrderWeMet = "<relationship fault: 0x7fb91bd17c20 'friendsInTheOrderWeMet'>";\n    house = nil;\n    houseID = 0;\n    housesOwned = "<relationship fault: 0x7fb91da8bd70 'housesOwned'>";\n    housesResidedAt = "<relationship fault: 0x7fb91da306f0 'housesResidedAt'>";\n    isHappy = nil;\n    landlord = nil;\n    likesDogs = 1;\n    mutableFavoriteColors = nil;\n    name = "My Name";\n    nickName = nil;\n    parties = "<relationship fault: 0x7fb91bf67700 'parties'>";\n    railsID = 1;\n    residence = nil;\n    roommates = "<relationship fault: 0x7fb91da8a2a0 'roommates'>";\n    sex = nil;\n    tenants = "<relationship fault: 0x7fb91da17070 'tenants'>";\n    updatedAt = nil;\n})
  /Users/travis/build/RestKit/RestKit/Tests/Logic/Network/RKManagedObjectRequestOperationTest.m:1495
  ```
    RKHuman *mappedHuman = [managedObjectRequestOperation.mappingResult firstObject];
    expect(mappedHuman).to.equal(human);
    NSUInteger count = [managedObjectStore.mainQueueManagedObjectContext countForEntityForName:@"Human" predicate:[NSPredicate predicateWithFormat:@"railsID = 1"] error:nil];
  ```
  testThatManuallyCreatedObjectsThatAreNotSavedBeforePostingAreNotDuplicatedWhenMappedWithInMemoryManagedObjectCache, expected: 1, got: 2
  /Users/travis/build/RestKit/RestKit/Tests/Logic/Network/RKManagedObjectRequestOperationTest.m:1497
  ```
    NSUInteger count = [managedObjectStore.mainQueueManagedObjectContext countForEntityForName:@"Human" predicate:[NSPredicate predicateWithFormat:@"railsID = 1"] error:nil];
    expect(count).to.equal(1);
}
```

What I would try, having the time, is to migrate the project to the latest dependencies (Cocoapods 1.2.0 and Xcode 8.2.1). Fix eventual CI issues and then make a release.

Having said that, the RestKit code runs just fine when installed in another project (I have been using it), it's the RestKit project itself that needs some love.

**Comment by arasu01** [comment]
Whether 0.27.1 version will be released soon?

**Comment by valeriomazzeo** [comment]
green!

**Pull request merged**
